# Generated by Django 5.2.12 on 2026-03-08 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('is_farmer_group', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FactoryThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_pluck', models.PositiveIntegerField(default=60)),
                ('max_moisture', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('max_foreign_matter', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='core.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeaBuyingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_centers', to='core.factory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('factory', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('intake_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.factory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.supplier')),
                ('buying_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.teabuyingcenter')),
            ],
            options={
                'ordering': ['-intake_date', 'batch_code'],
            },
        ),
    ]
