# Generated by Django 5.2.12 on 2026-03-08 23:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryIntakeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_timestamp', models.DateTimeField()),
                ('leaf_image', models.ImageField(upload_to='samples/')),
                ('client_submission_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('predicted_pluck_class', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
                ('predicted_pluck_score', models.PositiveIntegerField(default=0)),
                ('prediction_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('manual_override_pluck_score', models.PositiveIntegerField(blank=True, null=True)),
                ('moisture_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foreign_matter_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('quality_status', models.CharField(choices=[('Excellent', 'Excellent'), ('Acceptable', 'Acceptable'), ('Warning', 'Warning'), ('Reject', 'Reject')], default='Warning', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('Approve Batch', 'Approve Batch'), ('Reject Batch', 'Reject Batch'), ('Send for Re-sorting', 'Send for Re-sorting'), ('Hold for Review', 'Hold for Review')], max_length=30)),
                ('decision_reason', models.TextField(blank=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.batch')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_samples', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.factory')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspected_samples', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.supplier')),
                ('tea_buying_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.teabuyingcenter')),
            ],
            options={
                'ordering': ['-intake_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QualityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_PLUCK', 'LOW_PLUCK'), ('HIGH_MOISTURE', 'HIGH_MOISTURE'), ('HIGH_FOREIGN', 'HIGH_FOREIGN')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sampling.factoryintakesample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleDecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Approve Batch', 'Approve Batch'), ('Reject Batch', 'Reject Batch'), ('Send for Re-sorting', 'Send for Re-sorting'), ('Hold for Review', 'Hold for Review')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_history', to='sampling.factoryintakesample')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
    ]
