# Generated by Django 5.2.12 on 2026-03-21 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryintakesample',
            name='ai_label_grade',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factoryintakesample',
            name='ai_label_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factoryintakesample',
            name='ai_label_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labeled_ai_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factoryintakesample',
            name='ai_label_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
