# Generated by Django 5.2.12 on 2026-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_factoryintakesample_ai_label_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryintakesample',
            name='leaf_image',
            field=models.ImageField(blank=True, null=True, upload_to='samples/'),
        ),
    ]
